options:
    # Mandatory
    # ===
    app_tgz_url:
        description: "A url where a gzipped tarball of the application files can be downloaded"

    # Optional
    # ===
    wsgi_file_path:
        default: "app.py"
        description: "The location (within the project) of the WSGI script"

    wsgi_app_name:
        default: "app"
        description: "The name of the application inside the WSGI file"

    apt_dependencies:
        description: "Space separated list of extra apt packages to be installed."

    apache_conf_path:
        default: "templates/wsgi-app.conf"
        description: |
            Path within the project to an apache configuration template
            The template should be based off [charm]/templates/wsgi-app.conf

    nagios_check_uri:
        default: "/"
        description: |
            Relative URI for nagios to check against
            Nagios will expect a 200 status and a string, set in `nagios_check_string`

    nagios_check_string:
        default: ""
        description: The string for nagios to check is in the `nagios_check_uri` page

    ssl_keyfile:
        description: "Base64 encoded keyfile for SSL"

    ssl_certificate:
        description: "Base64 encoded certificate file for SSL"

    server_name:
        default: "*"
        description: "The servername for inclusion in the Apache configuration"

    static_path:
        default: "static"
        description: "The path to the static folder within the application"

    static_url_path:
        default: "static"
        description: "The URL path to access static files"

    pip_no_index:
        default: False
        type: boolean
        description: "Prevent pip connecting to Python Package Index to download packages"

    pip_requirements_path:
        default: "requirements.txt"
        description: |
            A path (within the project) to pip requirements file
            - set this to blank to prevent installing from PyPi

    pip_cache_path:
        default: "pip-cache"
        description: "A path (within the project) to python dependencies"

    environment_variables:
        description: "A dictionary of environment variables to be set in the instance"

    nagios_environment:
        default: "wsgi-apps"
        description: "Name of the environment for use in nagios"
