#!/usr/bin/env python

#from lib.tasks import TASKS

# Add config changed code here

# Preferably, encapsulate your business functions in lib/tasks.py
# and then import them above and run them in here
