#!/usr/bin/env python

import sys
from os import path
import sh

# Add ./lib to path
lib_dir = path.join(path.dirname(__file__), 'lib')
sys.path.append(lib_dir)

hostname = sh.unit_get('public-address', format='json')
sh.relation_set('hostname=%s' % hostname, format='json')
